language: cpp
dist: bionic
compiler:
  - gcc
  - clang
os:
  - linux
before_install:
  - sudo apt-get -y install libboost-test-dev flex bison
script:
  - cmake .
  - make all
after_success:
  - ./test_exe