#pragma once

#include "ArrayAccessExpression.hpp"
#include "ChrExpression.hpp"
#include "FunctionCallExpression.hpp"
#include "IdentifierExpression.hpp"
#include "LiteralExpression.hpp"
#include "OrdExpression.hpp"
#include "ParenthesisExpression.hpp"
#include "PredExpression.hpp"
#include "RecordAccessExpression.hpp"
#include "StringExpression.hpp"
#include "SuccExpression.hpp"

#include "UnaryOperators/NegExpression.hpp"
#include "UnaryOperators/NotExpression.hpp"

#include "BinaryOperators/AndExpression.hpp"
#include "BinaryOperators/OrExpression.hpp"
#include "BinaryOperators/EqualExpression.hpp"
#include "BinaryOperators/NotEqualExpression.hpp"
#include "BinaryOperators/LessExpression.hpp"
#include "BinaryOperators/LessEqualExpression.hpp"
#include "BinaryOperators/GreaterExpression.hpp"
#include "BinaryOperators/GreaterEqualExpression.hpp"
#include "BinaryOperators/AddExpression.hpp"
#include "BinaryOperators/SubExpression.hpp"
#include "BinaryOperators/MulExpression.hpp"
#include "BinaryOperators/DivExpression.hpp"
#include "BinaryOperators/ModExpression.hpp"
