#pragma once

#include "ASTNode.hpp"
#include "FrontEnd/AST/Expression/Expression.hpp"
#include "FrontEnd/AST/Expression/LiteralExpression.hpp"
#include "FrontEnd/AST/Expression/SuccExpression.hpp"
#include "FrontEnd/AST/Expression/PredExpression.hpp"
#include "FrontEnd/AST/Expression/OrdExpression.hpp"
#include "FrontEnd/AST/Expression/ChrExpression.hpp"
#include "FrontEnd/AST/Expression/LValue.hpp"
#include "FrontEnd/AST/Expression/RecordAccessExpression.hpp"
#include "FrontEnd/AST/Expression/IdentifierExpression.hpp"
#include "FrontEnd/AST/Expression/ArrayAccessExpression.hpp"
#include "FrontEnd/AST/Expression/FunctionCallExpression.hpp"
#include "FrontEnd/AST/Expression/BinaryOpExpression.hpp"
#include "FrontEnd/AST/Expression/UnaryOpExpression.hpp"
#include "Expression/ParenthesisExpression.hpp"